name: template
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  vibration: ^1.7.4-nullsafety.0
  flutter_bloc: any
  statusbarz: any
  get_it: any
  get: any
  get_storage: any
  cached_network_image: any
  flutter_svg: any
  logger: any
  flutter_native_splash: any
  firebase_core: any
  firebase_dynamic_links: any
  firebase_messaging: any
  firebase_in_app_messaging: any
  firebase_remote_config: any
  cloud_functions: any
  firebase_crashlytics: any
  cloud_firestore: any
  firebase_storage: any
  firebase_auth: any
  flutter_spinkit: any
  permission_handler: any
  flutter_fadein: any
  firebase_analytics: any

flutter_native_splash:
  background_image: "assets/splash_screen.png"
  fullscreen: true
  ios_content_mode: scaleAspectFill
  android_gravity: fill
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: L
